/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface I18nT {
        "tData": string;
    }
}
declare global {
    interface HTMLI18nTElement extends Components.I18nT, HTMLStencilElement {
    }
    var HTMLI18nTElement: {
        prototype: HTMLI18nTElement;
        new (): HTMLI18nTElement;
    };
    interface HTMLElementTagNameMap {
        "i18n-t": HTMLI18nTElement;
    }
}
declare namespace LocalJSX {
    interface I18nT {
        "tData"?: string;
    }
    interface IntrinsicElements {
        "i18n-t": I18nT;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "i18n-t": LocalJSX.I18nT & JSXBase.HTMLAttributes<HTMLI18nTElement>;
        }
    }
}
